Update android.yaml

diff --git a/.github/workflows/android.yaml b/.github/workflows/android.yaml
--- a/.github/workflows/android.yaml
+++ b/.github/workflows/android.yaml
@@ -38,8 +38,12 @@ jobs:
         name: app-debug-apk
     - name: Display structure of downloaded files
       run: ls -R
-    - name: Setup and validate Google Cloud credentials
+    - name: Verify and setup Google Cloud credentials
       run: |
+        if [ -z "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}" ]; then
+          echo "Error: GOOGLE_DRIVE_CREDENTIALS is empty"
+          exit 1
+        fi
         echo '${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}' > google-credentials.json
         echo "Credentials file created"
         if jq empty google-credentials.json 2>/dev/null; then
